### PR TITLE
Fix issue #70 - WAV encoding for mono recording

### PR DESCRIPTION
**Pull request by andpor**
Correct the WAV encoding for single channel or mono recording. byteRate field in the WAV header was incorrectly computed

### CODE REVIEW

**Comment by noahjerreel** [comment]
Hello @andpor does this audio work when recording to stereo type device, like laptops?

I created an issue regarding the audio got choppy when trying to record on laptop with 1 audio channel setting for the recorder

[https://github.com/streamproc/MediaStreamRecorder/issues/92](url)

**Comment by andpor** [comment]
I think there was a bug for stereo recording - the right buffer was getting leftChannel data. I fixed that part on this PR which unfortunately has not been merged yet...

**Comment by noahjerreel** [comment]
@andpor but did you test it? Is it working now?

**Comment by andpor** [comment]
So you decided not to merge this in? Can you explain why...just curious...

**Comment by andpor** [comment]
@noahjerreel  - my fix works fine.

**Comment by noahjerreel** [comment]
@andpor - I would love to test it but respect to @muaz-khan , will use his latest release. Sorry man!

**Comment by andpor** [comment]
Nothing to be sorry about - my fix in there...not directly merged but it is there...

**Comment by noahjerreel** [comment]
That's good then @andpor , right?

**Pull request closed without merging**
